apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-02-01T11:44:39Z"
  labels:
    run: busybox
  name: busybox
  namespace: default
  resourceVersion: "774832"
  uid: 50fd9b3a-1f1e-48d7-8e1e-72d8a57b090e
spec:
  containers:
  - args:
    - busybox
    image: busybox
    imagePullPolicy: Always
    name: busybox
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-f5k4g
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-f5k4g
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-02-01T11:44:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-02-01T11:44:39Z"
    message: 'containers with unready status: [busybox]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-02-01T11:44:39Z"
    message: 'containers with unready status: [busybox]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-02-01T11:44:39Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://db23e76043198a4f0593a142b763bcdf88de5d0b2251e5121ac9c28877994402
    image: busybox:latest
    imageID: docker-pullable://busybox@sha256:7b3ccabffc97de872a30dfd234fd972a66d247c8cfc69b0550f276481852627c
    lastState:
      terminated:
        containerID: docker://db23e76043198a4f0593a142b763bcdf88de5d0b2251e5121ac9c28877994402
        exitCode: 0
        finishedAt: "2023-02-01T11:46:20Z"
        reason: Completed
        startedAt: "2023-02-01T11:46:20Z"
    name: busybox
    ready: false
    restartCount: 4
    started: false
    state:
      waiting:
        message: back-off 1m20s restarting failed container=busybox pod=busybox_default(50fd9b3a-1f1e-48d7-8e1e-72d8a57b090e)
        reason: CrashLoopBackOff
  hostIP: 192.168.65.4
  phase: Running
  podIP: 10.1.0.214
  podIPs:
  - ip: 10.1.0.214
  qosClass: BestEffort
  startTime: "2023-02-01T11:44:39Z"
